env:
  global:
  - CC_TEST_REPORTER_ID=$CCKEY
language: node_js
node_js:
- '14'
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
- npm run build
- npm run eslint
script:
- npm run test -- --coverage
after_script:
- "./cc-test-reporter after-build -t lcov --debug --exit-code $TRAVIS_TEST_RESULT"
deploy:
  provider: npm
  email: azawakhh@gmail.com
  api_key: $NPM_TOKEN
  on:
    tags: true
    repo: azawakh/twsh
  skip_cleanup: true
